//! Auto-generated by scripts/gen-js-fragments.js — do not edit manually.
//! Regenerate: node scripts/gen-js-fragments.js
//! Verify:     node scripts/gen-js-fragments.js --check  (runs in `zig build drift`)
//! Source:     the `fragments` object in that script — NOT js-html-template.mjs,
//!             which is a readable mirror nothing reads at build time.

pub const stop_prev = "let R;window.__pngineStop?.();";
pub const stop_reg = "window.__pngineStop=()=>{cancelAnimationFrame(R),d.destroy()};";
pub const device_lost = "d.lost.then(()=>cancelAnimationFrame(R));";
pub const fs_setup = "c.width=innerWidth*devicePixelRatio,c.height=innerHeight*devicePixelRatio;";
pub const webgpu_init = "let a=await navigator.gpu.requestAdapter(),d=await a.requestDevice(),x=c.getContext('webgpu'),f=navigator.gpu.getPreferredCanvasFormat();x.configure({device:d,format:f});";
pub const webgpu_init_limits = "let a=await navigator.gpu.requestAdapter(),d=await a.requestDevice(L),x=c.getContext('webgpu'),f=navigator.gpu.getPreferredCanvasFormat();x.configure({device:d,format:f});";
pub const decompress = "let D=s=>new Response(new Blob([Uint8Array.from(atob(s),c=>c.charCodeAt(0))]).stream().pipeThrough(new DecompressionStream('deflate-raw'))).text();";
pub const pointer = "let px=0,py=0,pcx=0,pcy=0,pdx=0,pdy=0,pbt=0,ppr=0,pm=0,psx=0,psy=0,lx=0,ly=0;c.onpointerdown=e=>{let r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;px=x,py=y,pcx=x,pcy=y,pbt=e.buttons,ppr=e.pressure||.5,pm=(e.shiftKey?1:0)|(e.ctrlKey?2:0)|(e.altKey?4:0)|(e.metaKey?8:0)|16&pm,lx=x,ly=y,c.setPointerCapture(e.pointerId)},c.onpointermove=e=>{let r=c.getBoundingClientRect(),x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));pdx+=x-lx,pdy+=y-ly,px=x,py=y,pbt=e.buttons,ppr=e.pressure||(e.buttons?.5:0),pm=(e.shiftKey?1:0)|(e.ctrlKey?2:0)|(e.altKey?4:0)|(e.metaKey?8:0)|16&pm,lx=x,ly=y},c.onpointerup=()=>{pcx=-Math.abs(pcx),pcy=-Math.abs(pcy),pbt=0,ppr=0},c.onpointercancel=c.onpointerup,document.onkeydown=e=>{'Space'===e.code&&(pm|=16)},document.onkeyup=e=>{'Space'===e.code&&(pm&=-17)},c.onwheel=e=>{e.preventDefault(),psx+=Math.sign(e.deltaX),psy+=Math.sign(e.deltaY),pm=(e.shiftKey?1:0)|(e.ctrlKey?2:0)|(e.altKey?4:0)|(e.metaKey?8:0)|16&pm};";
pub const dark_setup = "let dkq=()=>{try{return localStorage.getItem('pngine-dark')}catch{return null}},dkm=matchMedia('(prefers-color-scheme:dark)'),dk=+(dkq()??dkm.matches);dkm.onchange=e=>{null==dkq()&&(dk=+e.matches)},onstorage=e=>{'pngine-dark'===e.key&&(dk=+(e.newValue??dkm.matches))};";
pub const audio_pre = "let{instance:ai}=await WebAssembly.instantiate(Uint8Array.from(atob('";
pub const audio_post = "'),c=>c.charCodeAt(0)),{m:Math}),am=ai.exports.m,as=ai.exports.s.value,al=ai.exports.l.value,at=1==ai.exports.t.value,afr=at?al/4:al/8,asp=at?new Int16Array(am.buffer,as,2*afr):new Float32Array(am.buffer,as,2*afr),ax=new AudioContext({sampleRate:44100}),ab=ax.createBuffer(2,afr,44100),sr;for(let c=0;c<2;c++){let d=ab.getChannelData(c);for(let i=0;i<afr;i++)d[i]=at?asp[2*i+c]/32768:asp[2*i+c]};";
pub const anim_start = "let t0;function F(){let t=(performance.now()-t0)/1e3;";
pub const anim_end = "R=requestAnimationFrame(F)}";
pub const esc_handler = "onkeydown=e=>e.which-27||history.go();";
pub const click_handler = "c.onclick=()=>{t0=performance.now(),F(),c.onclick=0};";
pub const click_handler_audio_pre = "p.onclick=()=>{p.remove(),t0=performance.now(),";
pub const click_audio_start = "ax&&('suspended'==ax.state&&ax.resume(),sr=ax.createBufferSource(),sr.buffer=ab,sr.connect(ax.destination),sr.start(0,0))";
pub const click_handler_audio_post = ",F()};";
pub const click_handler_audiojs_pre = "p.onclick=()=>{p.remove(),t0=performance.now(),s(),";
pub const click_handler_audiojs_fft_pre = "p.onclick=()=>{p.remove(),t0=performance.now(),_af=s(),";
pub const click_handler_audiojs_post = "F()};";
