//! TypeScript Type Generator
//!
//! Generates TypeScript type definitions (.d.ts) from uniform table metadata.
//! Enables type-safe setUniform() calls in TypeScript applications.
//!
//! ## Usage
//! ```bash
//! pngine shader.sjon --types  # Outputs shader.d.ts alongside PNG
//! ```
//!
//! ## Generated Format
//! ```typescript
//! export interface Uniforms {
//!   time: number;
//!   "position.x": number;
//!   color: [number, number, number, number];
//! }
//! export type UniformName = keyof Uniforms;
//! ```
//!
//! ## Invariants
//! - Output file is valid TypeScript
//! - One property per distinct field name; when the same name appears in
//!   several binding records the LAST one wins, matching gpu.js setUniform
//! - Type mappings follow WGSL to TypeScript conventions

const std = @import("std");
const assert = std.debug.assert;
const Allocator = std.mem.Allocator;

const pngine = @import("pngine");
const format = pngine.format;
const UniformType = pngine.uniform_table.UniformType;
const UniformTable = pngine.uniform_table.UniformTable;
const StringTable = pngine.string_table.StringTable;

/// Maximum output size for generated TypeScript (safety limit).
const MAX_OUTPUT_SIZE: u32 = 64 * 1024;

/// Generate TypeScript type definitions from bytecode.
///
/// Pre-condition: bytecode is valid PNGB format.
/// Post-condition: Returns owned TypeScript source that caller must free.
pub fn generateFromBytecode(allocator: Allocator, bytecode: []const u8) ![]u8 {
    // Pre-conditions
    assert(bytecode.len >= format.HEADER_SIZE);
    assert(std.mem.eql(u8, bytecode[0..4], format.MAGIC));

    // Deserialize to get uniform table and string table
    var module = try format.deserialize(allocator, bytecode);
    defer module.deinit(allocator);

    return generate(allocator, &module.uniforms, &module.strings);
}

/// Generate TypeScript type definitions from uniform table.
///
/// Pre-condition: uniforms and strings are valid.
/// Post-condition: Returns owned TypeScript source that caller must free.
pub fn generate(
    allocator: Allocator,
    uniforms: *const UniformTable,
    strings: *const StringTable,
) ![]u8 {
    // Pre-conditions
    assert(@intFromPtr(uniforms) != 0);
    assert(@intFromPtr(strings) != 0);

    var output = std.ArrayList(u8).empty;
    errdefer output.deinit(allocator);

    // Write header comment
    try output.appendSlice(allocator,
        \\// Auto-generated by pngine - DO NOT EDIT
        \\// Uniform type definitions for setUniform() API
        \\
        \\
    );

    var last_index: std.StringHashMapUnmanaged(u32) = .empty;
    defer last_index.deinit(allocator);
    const total_fields = try indexLastOccurrences(allocator, uniforms, strings, &last_index);

    if (total_fields == 0) {
        // No uniforms - generate empty interface
        try output.appendSlice(allocator,
            \\export interface Uniforms {}
            \\export type UniformName = never;
            \\
        );
        return try output.toOwnedSlice(allocator);
    }

    try output.appendSlice(allocator, "export interface Uniforms {\n");
    try emitFields(allocator, &output, uniforms, strings, &last_index, total_fields);
    try output.appendSlice(allocator, "}\n\n");

    // Write UniformName type alias
    try output.appendSlice(allocator, "export type UniformName = keyof Uniforms;\n");

    // Post-condition: output is bounded
    assert(output.items.len <= MAX_OUTPUT_SIZE);

    return try output.toOwnedSlice(allocator);
}

/// Record each field name's *last* flat occurrence, returning the field count.
///
/// The table can list one buffer twice with disagreeing field maps, and gpu.js
/// setUniform keys by bare name doc-wide (last parsed wins) — the interface must
/// collapse duplicates the same way or the TS has duplicate identifiers.
fn indexLastOccurrences(
    allocator: Allocator,
    uniforms: *const UniformTable,
    strings: *const StringTable,
    last_index: *std.StringHashMapUnmanaged(u32),
) !u32 {
    assert(last_index.count() == 0);

    var total_fields: u32 = 0;
    for (uniforms.bindings.items) |binding| {
        for (binding.fields) |field| {
            const field_name = strings.get(@enumFromInt(field.name_string_id));
            try last_index.put(allocator, field_name, total_fields);
            total_fields += 1;
        }
    }

    assert(last_index.count() <= total_fields);
    return total_fields;
}

/// Write one `name: type;` line per surviving field, in table order.
fn emitFields(
    allocator: Allocator,
    output: *std.ArrayList(u8),
    uniforms: *const UniformTable,
    strings: *const StringTable,
    last_index: *const std.StringHashMapUnmanaged(u32),
    total_fields: u32,
) !void {
    assert(total_fields > 0);

    var index: u32 = 0;
    for (uniforms.bindings.items) |binding| {
        for (binding.fields) |field| {
            const field_name = strings.get(@enumFromInt(field.name_string_id));
            const emit_here = (last_index.get(field_name) orelse unreachable) == index;
            index += 1;
            if (!emit_here) continue;
            // An array field (elem_count > 0) takes a whole flat value of
            // elem_count × element lanes — a plain number[] is the honest
            // type; the element tuple would claim one element's shape.
            const ts_type = if (field.elem_count > 0)
                "number[]"
            else
                uniformTypeToTypeScript(field.uniform_type);

            // Quote field names with dots (nested fields). The format string
            // must be comptime, so the branch is on the call, not the string.
            const line = if (std.mem.indexOf(u8, field_name, ".") != null)
                try std.fmt.allocPrint(allocator, "  \"{s}\": {s};\n", .{ field_name, ts_type })
            else
                try std.fmt.allocPrint(allocator, "  {s}: {s};\n", .{ field_name, ts_type });
            defer allocator.free(line);
            try output.appendSlice(allocator, line);
        }
    }

    assert(index == total_fields);
}

/// Map UniformType to TypeScript type string.
///
/// Pre-condition: uniform_type is a valid UniformType.
/// Post-condition: Returns a valid TypeScript type string.
fn uniformTypeToTypeScript(uniform_type: UniformType) []const u8 {
    return switch (uniform_type) {
        // Scalar types
        .f32, .i32, .u32 => "number",

        // Vector types (tuples)
        .vec2f, .vec2i, .vec2u => "[number, number]",
        .vec3f, .vec3i, .vec3u => "[number, number, number]",
        .vec4f, .vec4i, .vec4u => "[number, number, number, number]",

        // Matrix types (nested tuples, column-major)
        .mat3x3f => "[[number, number, number], [number, number, number], [number, number, number]]",
        .mat4x4f => "[[number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number]]",

        // Unknown - use generic ArrayLike
        .unknown => "ArrayLike<number>",
    };
}

/// Write TypeScript definitions to file.
///
/// Pre-condition: path ends with .d.ts, content is valid TypeScript.
/// Post-condition: File is written or error returned.
pub fn writeToFile(io: std.Io, path: []const u8, content: []const u8) !void {
    // Pre-condition
    assert(path.len > 5); // At least "x.d.ts"
    assert(std.mem.endsWith(u8, path, ".d.ts"));

    const file = try std.Io.Dir.cwd().createFile(io, path, .{});
    defer file.close(io);

    try file.writeStreamingAll(io, content);
}

/// Derive .d.ts path from PNG/bytecode output path.
///
/// Pre-condition: output_path is a valid path.
/// Post-condition: Returns owned path that caller must free.
pub fn deriveTypesPath(allocator: Allocator, output_path: []const u8) ![]u8 {
    // Pre-condition
    assert(output_path.len > 0);

    const stem = std.fs.path.stem(output_path);
    const dir = std.fs.path.dirname(output_path);

    const result = if (dir) |d|
        try std.fmt.allocPrint(allocator, "{s}/{s}.d.ts", .{ d, stem })
    else
        try std.fmt.allocPrint(allocator, "{s}.d.ts", .{stem});

    // Post-condition
    assert(std.mem.endsWith(u8, result, ".d.ts"));

    return result;
}

// ============================================================================
// Tests
// ============================================================================

const testing = std.testing;

/// Intern a name and return the raw u16 the wire structs carry
/// (`StringId` is a typed index; `name_string_id` fields are u16).
fn internU16(strings: *StringTable, name: []const u8) !u16 {
    return @intFromEnum(try strings.intern(testing.allocator, name));
}
