import SwiftUI
import PngineKit

// Rotating cube bytecode (6316 bytes)
let cubeBytecode = Data(base64Encoded: """
UE5HQgAAAAABAAAAAAAAAAAAAABoAAAApAAAAHYYAAB5GAAAqxgAAAQAAQEAhaAoIAAAAAEBEEgCAAIIAAMKAAAEMwAABRDAAP/+AQAAEgAUAAATAAAWJAEAABk0MAAAKgEAEDIAJDEGAAAABAAKABEAGAAcAAQABgAHAAcABAAGAGN1YmVhc3BlY3RjYW52YXNIY2FudmFzV3RpbWVpbnB1dHMGAAAAAACgBQAAoAUAACAQAADAFQAACAAAAMgVAADCAQAAihcAABQAAACeFwAAAgAAAAAAgD8AAIC/AACAPwAAgD8AAAA/AAAAAAAAAD8AAIA/AAAAAAAAgD8AAIC/AACAvwAAgD8AAIA/AAAAPwAAAAAAAAA/AACAPwAAgD8AAIA/AACAvwAAgL8AAIC/AACAPwAAAD8AAAAAAAAAPwAAgD8AAIA/AAAAAAAAgD8AAIC/AACAvwAAgD8AAAA/AAAAAAAAAD8AAIA/AAAAAAAAAAAAAIA/AACAvwAAgD8AAIA/AAAAPwAAAAAAAAA/AACAPwAAAAAAAIA/AACAvwAAgL8AAIC/AACAPwAAAD8AAAAAAAAAPwAAgD8AAIA/AAAAAAAAgD8AAIA/AACAPwAAgD8AAIA/AAAAPwAAAD8AAIA/AAAAAAAAgD8AAIA/AACAvwAAgD8AAIA/AACAPwAAAD8AAAA/AACAPwAAgD8AAIA/AACAPwAAgL8AAIC/AACAPwAAgD8AAAA/AAAAPwAAgD8AAIA/AAAAAAAAgD8AAIA/AACAvwAAgD8AAIA/AAAAPwAAAD8AAIA/AAAAAAAAAAAAAIA/AACAPwAAgD8AAIA/AACAPwAAAD8AAAA/AACAPwAAAAAAAIA/AACAPwAAgL8AAIC/AACAPwAAgD8AAAA/AAAAPwAAgD8AAIA/AAAAAAAAgL8AAIA/AACAPwAAgD8AAAA/AACAPwAAAD8AAIA/AAAAAAAAgD8AAIA/AACAPwAAgD8AAIA/AAAAPwAAgD8AAAA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIC/AACAPwAAAD8AAIA/AAAAPwAAgD8AAIA/AAAAAAAAgL8AAIA/AACAvwAAgD8AAAA/AACAPwAAAD8AAIA/AAAAAAAAAAAAAIC/AACAPwAAgD8AAIA/AAAAPwAAgD8AAAA/AACAPwAAAAAAAIA/AACAPwAAgD8AAIC/AACAPwAAAD8AAIA/AAAAPwAAgD8AAIA/AAAAAAAAgL8AAIC/AACAPwAAgD8AAAAAAAAAPwAAAD8AAIA/AAAAAAAAgD8AAIC/AACAPwAAgD8AAIA/AAAAAAAAAD8AAAA/AACAPwAAgD8AAIA/AACAvwAAgD8AAIC/AACAPwAAAAAAAAA/AAAAPwAAgD8AAIA/AAAAAAAAgL8AAIC/AACAvwAAgD8AAAAAAAAAPwAAAD8AAIA/AAAAAAAAAAAAAIC/AACAvwAAgD8AAIA/AAAAAAAAAD8AAAA/AACAPwAAAAAAAIA/AACAvwAAgD8AAIC/AACAPwAAAAAAAAA/AAAAPwAAgD8AAIA/AAAAAAAAgD8AAIA/AACAPwAAgD8AAAA/AAAAPwAAgD8AAIA/AAAAAAAAgD8AAIC/AACAPwAAgD8AAIA/AAAAPwAAAD8AAIA/AACAPwAAgD8AAIA/AACAvwAAgL8AAIA/AACAPwAAAD8AAAA/AACAPwAAgD8AAIA/AAAAAAAAgD8AAIC/AACAPwAAgD8AAAA/AAAAPwAAgD8AAIA/AAAAAAAAAAAAAIA/AACAPwAAgD8AAIA/AAAAPwAAAD8AAIA/AACAPwAAAAAAAIA/AACAvwAAgL8AAIA/AACAPwAAAD8AAAA/AACAPwAAgD8AAIA/AAAAAAAAgD8AAIC/AACAvwAAgD8AAAA/AAAAPwAAAD8AAIA/AAAAAAAAgD8AAIC/AACAvwAAgL8AAIA/AAAAPwAAAD8AAAA/AACAPwAAgD8AAIA/AACAvwAAgD8AAIC/AACAPwAAAD8AAAA/AAAAPwAAgD8AAIA/AAAAAAAAgD8AAIA/AACAvwAAgD8AAAA/AAAAPwAAAD8AAIA/AAAAAAAAAAAAAIA/AACAvwAAgL8AAIA/AAAAPwAAAD8AAAA/AACAPwAAAAAAAIA/AACAvwAAgD8AAIC/AACAPwAAAD8AAAA/AAAAPwAAgD8AAIA/AAAAAApzdHJ1Y3QgUG5naW5lSW5wdXRzIHsKICB0aW1lOiBmMzIsCiAgY2FudmFzVzogZjMyLAogIGNhbnZhc0g6IGYzMiwKICBhc3BlY3Q6IGYzMiwKfTsKQGdyb3VwKDApIEBiaW5kaW5nKDApIHZhcjx1bmlmb3JtPiBpbnB1dHMgOiBQbmdpbmVJbnB1dHM7CgoKZm4gcGVyc3BlY3RpdmUoZmllbGRPZlZpZXdZOiBmMzIsIGFzcGVjdDogZjMyLCB6TmVhcjogZjMyLCB6RmFyOiBmMzIpIC0+IG1hdDR4NDxmMzI+IHsKICAgIC8vIENvbXB1dGUgZiA9IHRhbijPgC8yIC0gZmllbGRPZlZpZXdZLzIpIHdoaWNoIGlzIGVxdWl2YWxlbnQgdG8gMS90YW4oZmllbGRPZlZpZXdZLzIpCiAgICBsZXQgZjogZjMyID0gdGFuKDAuNSAqIDMuMTQxNTkyNjUzNTg5NzkzIC0gMC41ICogZmllbGRPZlZpZXdZKTsKICAgIAogICAgdmFyIEE6IGYzMjsKICAgIHZhciBCOiBmMzI7CiAgICBsZXQgcmFuZ2VJbnY6IGYzMiA9IDEuMCAvICh6TmVhciAtIHpGYXIpOwogICAgQSA9IHpGYXIgKiByYW5nZUludjsKICAgIEIgPSB6RmFyICogek5lYXIgKiByYW5nZUludjsKICAgIAogICAgLy8gQ29uc3RydWN0IHRoZSBtYXRyaXggaW4gY29sdW1uLW1ham9yIG9yZGVyOgogICAgLy8gQ29sdW1uIDA6IChmL2FzcGVjdCwgMCwgMCwgMCkKICAgIC8vIENvbHVtbiAxOiAoMCwgZiwgMCwgMCkKICAgIC8vIENvbHVtbiAyOiAoMCwgMCwgQSwgLTEpCiAgICAvLyBDb2x1bW4gMzogKDAsIDAsIEIsIDApCiAgICByZXR1cm4gbWF0NHg0PGYzMj4oCiAgICAgICAgdmVjNDxmMzI+KGYgLyBhc3BlY3QsIDAuMCwgICAwLjAsIDAuMCksCiAgICAgICAgdmVjNDxmMzI+KDAuMCwgICAgICAgIGYsICAgICAwLjAsIDAuMCksCiAgICAgICAgdmVjNDxmMzI+KDAuMCwgICAgICAgIDAuMCwgICBBLCAgLTEuMCksCiAgICAgICAgdmVjNDxmMzI+KDAuMCwgICAgICAgIDAuMCwgICBCLCAgMC4wKQogICAgKTsKfQoKZm4gZ2V0VHJhbnNmb3JtYXRpb25NYXRyaXgobm93OiBmMzIsIHByb2plY3Rpb25NYXRyaXg6IG1hdDR4NDxmMzI+KSAtPiBtYXQ0eDQ8ZjMyPiB7CiAgICAvLyBDcmVhdGUgYW4gaWRlbnRpdHkgbWF0cml4LgogICAgdmFyIHZpZXdNYXRyaXg6IG1hdDR4NDxmMzI+ID0gbWF0NHg0PGYzMj4oCiAgICAgICAgdmVjNDxmMzI+KDEuMCwgMC4wLCAwLjAsIDAuMCksCiAgICAgICAgdmVjNDxmMzI+KDAuMCwgMS4wLCAwLjAsIDAuMCksCiAgICAgICAgdmVjNDxmMzI+KDAuMCwgMC4wLCAxLjAsIDAuMCksCiAgICAgICAgdmVjNDxmMzI+KDAuMCwgMC4wLCAwLjAsIDEuMCkKICAgICk7CiAgICAKICAgIC8vIEJ1aWxkIGEgdHJhbnNsYXRpb24gbWF0cml4IHRvIG1vdmUgYWxvbmcgeiBieSAtNC4KICAgIGxldCB0cmFuc2xhdGlvbjogbWF0NHg0PGYzMj4gPSBtYXQ0eDQ8ZjMyPigKICAgICAgICB2ZWM0PGYzMj4oMS4wLCAwLjAsIDAuMCwgMC4wKSwKICAgICAgICB2ZWM0PGYzMj4oMC4wLCAxLjAsIDAuMCwgMC4wKSwKICAgICAgICB2ZWM0PGYzMj4oMC4wLCAwLjAsIDEuMCwgMC4wKSwKICAgICAgICB2ZWM0PGYzMj4oMC4wLCAwLjAsIC00LjAsIDEuMCkKICAgICk7CiAgICAvLyBBcHBseSB0aGUgdHJhbnNsYXRpb246IHZpZXdNYXRyaXggPSB2aWV3TWF0cml4ICogdHJhbnNsYXRpb24uCiAgICB2aWV3TWF0cml4ID0gdmlld01hdHJpeCAqIHRyYW5zbGF0aW9uOwogICAgCiAgICAvLyBCdWlsZCBhIHJvdGF0aW9uIG1hdHJpeC4KICAgIC8vIFJvdGF0aW9uIGFuZ2xlIChpbiByYWRpYW5zKS4KICAgIGxldCBhbmdsZTogZjMyID0gMS4wOwogICAgLy8gUm90YXRpb24gYXhpczogKHNpbihub3cpLCBjb3Mobm93KSwgMCkuCiAgICBsZXQgYXhpczogdmVjMzxmMzI+ID0gdmVjMzxmMzI+KHNpbihub3cpLCBjb3Mobm93KSwgMC4wKTsKICAgIC8vIFNpbmNlIHNpbsKyKG5vdykrY29zwrIobm93KT09MSwgdGhlIGF4aXMgaXMgYWxyZWFkeSBub3JtYWxpemVkLgogICAgbGV0IGM6IGYzMiA9IGNvcyhhbmdsZSk7CiAgICBsZXQgczogZjMyID0gc2luKGFuZ2xlKTsKICAgIGxldCB0OiBmMzIgPSAxLjAgLSBjOwogICAgbGV0IHg6IGYzMiA9IGF4aXMueDsKICAgIGxldCB5OiBmMzIgPSBheGlzLnk7CiAgICBsZXQgejogZjMyID0gYXhpcy56OyAvLyBUaGlzIGlzIDAuCiAgICAKICAgIC8vIENvbnN0cnVjdCB0aGUgNHg0IHJvdGF0aW9uIG1hdHJpeCAoZW1iZWRkZWQgaW4gNHg0KS4KICAgIGxldCByb3RhdGlvbjogbWF0NHg0PGYzMj4gPSBtYXQ0eDQ8ZjMyPigKICAgICAgICB2ZWM0PGYzMj4odCAqIHggKiB4ICsgYywgICAgIHQgKiB4ICogeSAtIHMgKiB6LCAgIHQgKiB4ICogeiArIHMgKiB5LCAgIDAuMCksCiAgICAgICAgdmVjNDxmMzI+KHQgKiB4ICogeSArIHMgKiB6LCAgIHQgKiB5ICogeSArIGMsICAgICAgIHQgKiB5ICogeiAtIHMgKiB4LCAgIDAuMCksCiAgICAgICAgdmVjNDxmMzI+KHQgKiB4ICogeiAtIHMgKiB5LCAgIHQgKiB5ICogeiArIHMgKiB4LCAgIHQgKiB6ICogeiArIGMsICAgICAgIDAuMCksCiAgICAgICAgdmVjNDxmMzI+KDAuMCwgICAgICAgICAgICAgICAwLjAsICAgICAgICAgICAgICAgICAwLjAsICAgICAgICAgICAgICAgICAxLjApCiAgICApOwogICAgLy8gQXBwbHkgdGhlIHJvdGF0aW9uOiB2aWV3TWF0cml4ID0gdmlld01hdHJpeCAqIHJvdGF0aW9uLgogICAgdmlld01hdHJpeCA9IHZpZXdNYXRyaXggKiByb3RhdGlvbjsKICAgIAogICAgLy8gQ29tYmluZSB3aXRoIHRoZSBwcm9qZWN0aW9uIG1hdHJpeC4KICAgIGxldCBtb2RlbFZpZXdQcm9qZWN0aW9uTWF0cml4OiBtYXQ0eDQ8ZjMyPiA9IHByb2plY3Rpb25NYXRyaXggKiB2aWV3TWF0cml4OwogICAgCiAgICByZXR1cm4gbW9kZWxWaWV3UHJvamVjdGlvbk1hdHJpeDsKfQoKc3RydWN0IFZlcnRleE91dHB1dCB7CiAgQGJ1aWx0aW4ocG9zaXRpb24pIFBvc2l0aW9uIDogdmVjNGYsCiAgQGxvY2F0aW9uKDApIGZyYWdDb2xvciA6IHZlYzRmLAogIEBsb2NhdGlvbigxKSBmcmFnVVYgOiB2ZWMyZiwKfTsKCkB2ZXJ0ZXgKZm4gdmVydGV4TWFpbigKICBAbG9jYXRpb24oMCkgcG9zaXRpb24gOiB2ZWM0ZiwKICBAbG9jYXRpb24oMSkgY29sb3IgOiB2ZWM0ZiwKICBAbG9jYXRpb24oMikgdXYgOiB2ZWMyZgopIC0+IFZlcnRleE91dHB1dCB7CiAgdmFyIG91dHB1dCA6IFZlcnRleE91dHB1dDsKCiAgLy8gU2ltcGxlIHJvdGF0aW9uIGFyb3VuZCBZIGF4aXMKICBsZXQgdCA9IGlucHV0cy50aW1lOwogIGxldCBjb3NUID0gY29zKHQpOwogIGxldCBzaW5UID0gc2luKHQpOwoKICAvLyBSb3RhdGUgWCBhbmQgWgogIGxldCByb3RYID0gcG9zaXRpb24ueCAqIGNvc1QgLSBwb3NpdGlvbi56ICogc2luVDsKICBsZXQgcm90WiA9IHBvc2l0aW9uLnggKiBzaW5UICsgcG9zaXRpb24ueiAqIGNvc1Q7CiAgbGV0IHJvdFkgPSBwb3NpdGlvbi55OwoKICAvLyBTaW1wbGUgcGVyc3BlY3RpdmU6IHNjYWxlIGJ5IGRpc3RhbmNlIGZyb20gY2FtZXJhCiAgLy8gQ2FtZXJhIGF0IHo9NCBsb29raW5nIGF0IG9yaWdpbgogIGxldCB2aWV3WiA9IHJvdFogLSA0LjA7ICAvLyBNb3ZlIGN1YmUgYmFjayBmcm9tIGNhbWVyYQogIGxldCBwZXJzcFNjYWxlID0gMS4wIC8gKC12aWV3Wik7ICAvLyBQZXJzcGVjdGl2ZSBkaXZpZGUgKHZpZXdaIGlzIG5lZ2F0aXZlKQoKICAvLyBNYXAgdG8gY2xpcCBzcGFjZQogIC8vIFdlYkdQVSBOREM6IHgseSBpbiBbLTEsMV0sIHogaW4gWzAsMV0KICBsZXQgY2xpcFggPSByb3RYICogcGVyc3BTY2FsZTsKICBsZXQgY2xpcFkgPSByb3RZICogcGVyc3BTY2FsZTsKICAvLyBNYXAgdmlld1ogZnJvbSBbLTUsIC0zXSB0byB6IFswLjMsIDAuN10gYXBwcm94aW1hdGVseQogIGxldCBjbGlwWiA9ICgtdmlld1ogLSAxLjApIC8gMTAuMDsgIC8vIFNpbXBsZSBsaW5lYXIgbWFwcGluZwoKICBvdXRwdXQuUG9zaXRpb24gPSB2ZWM0ZihjbGlwWCwgY2xpcFksIGNsaXBaLCAxLjApOwogIG91dHB1dC5mcmFnQ29sb3IgPSBjb2xvcjsKICBvdXRwdXQuZnJhZ1VWID0gdXY7CiAgcmV0dXJuIG91dHB1dDsKfQoKQGZyYWdtZW50CmZuIGZyYWdNYWluKAogIEBsb2NhdGlvbigwKSBmcmFnQ29sb3IgOiB2ZWM0ZiwKICBAbG9jYXRpb24oMSkgZnJhZ1VWIDogdmVjMmYKKSAtPiBAbG9jYXRpb24oMCkgdmVjNGYgewogIHJldHVybiBmcmFnQ29sb3I7Cn0KCgECBwcQCAcQeyJ2ZXJ0ZXgiOnsic2hhZGVyIjowLCJlbnRyeVBvaW50IjoidmVydGV4TWFpbiIsImJ1ZmZlcnMiOlt7ImFycmF5U3RyaWRlIjo0MCwiYXR0cmlidXRlcyI6W3sic2hhZGVyTG9jYXRpb24iOjAsIm9mZnNldCI6MCwiZm9ybWF0IjoiZmxvYXQzMng0In0seyJzaGFkZXJMb2NhdGlvbiI6MSwib2Zmc2V0IjoxNiwiZm9ybWF0IjoiZmxvYXQzMng0In0seyJzaGFkZXJMb2NhdGlvbiI6Miwib2Zmc2V0IjozMiwiZm9ybWF0IjoiZmxvYXQzMngyIn1dfV19LCJmcmFnbWVudCI6eyJzaGFkZXIiOjAsImVudHJ5UG9pbnQiOiJmcmFnTWFpbiJ9LCJwcmltaXRpdmUiOnsidG9wb2xvZ3kiOiJ0cmlhbmdsZS1saXN0IiwiY3VsbE1vZGUiOiJiYWNrIn0sImRlcHRoU3RlbmNpbCI6eyJkZXB0aFdyaXRlRW5hYmxlZCI6dHJ1ZSwiZGVwdGhDb21wYXJlIjoibGVzcyIsImZvcm1hdCI6ImRlcHRoMjRwbHVzIn19AwIBBwACAwEAAAEAAAAAAAAAAAB7fQEBAAEAAQAFAAAABAAAAAEADAAEAAAAAQACAAgABAAAAAIAAwAEAAQAAAADAAQAAAAEAAAAAA==
""")!

struct ContentView: View {
    @State private var status = "Tap to initialize"
    @State private var isInitialized = false
    @State private var version = ""
    @State private var bytecodeStatus = ""

    var body: some View {
        VStack(spacing: 16) {
            Text("PNGine iOS Test")
                .font(.largeTitle)
                .fontWeight(.bold)

            Text(status)
                .font(.body)
                .foregroundColor(isInitialized ? .green : .orange)

            if !version.isEmpty {
                Text("Version: \(version)")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }

            Text(bytecodeStatus)
                .font(.caption)
                .foregroundColor(.secondary)

            // Show PngineView with cube bytecode only when initialized
            if isInitialized {
                PngineView(bytecode: cubeBytecode)
                    .frame(width: 300, height: 300)
                    .background(Color.black)
                    .cornerRadius(12)
            } else {
                Rectangle()
                    .fill(Color.black)
                    .frame(width: 300, height: 300)
                    .cornerRadius(12)
            }

            Button(action: testInit) {
                Label("Test Initialize", systemImage: "play.fill")
            }
            .buttonStyle(.borderedProminent)
            .controlSize(.large)
        }
        .padding()
        .onAppear {
            bytecodeStatus = "Bytecode: \(cubeBytecode.count) bytes"
            // Auto-init after a short delay for testing
            DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
                testInit()
            }
        }
    }

    func testInit() {
        status = "Testing PngineKit..."

        // Get version first (this is safe, doesn't init GPU)
        version = pngineVersion()

        // Initialize PNGine
        let result = pngine_init()

        if result == 0 {
            status = "PNGine initialized!"
            isInitialized = true
        } else {
            let error = pngineLastError() ?? "Unknown error"
            status = "Init failed: \(error)"
            isInitialized = false
        }
    }
}

#Preview {
    ContentView()
}
