#!/usr/bin/env node
// Regenerate the section index at the top of docs/journal.md.
//
// The journal is ~12,500 lines and 250+ sections with no way to find anything
// short of grepping `### N.`. This builds a `§N — title` index from the
// headers themselves, so it cannot drift from the content the way a
// hand-maintained list would.
//
// The index is written between two HTML-comment markers; everything outside
// them is untouched, which keeps the file append-only in practice — adding a
// section and re-running only ever appends one line to the index.
//
// Usage:
//   node scripts/journal-toc.mjs           # rewrite the index in place
//   node scripts/journal-toc.mjs --check   # exit 1 if stale (CI drift gate)

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const JOURNAL = resolve(__dirname, '../docs/journal.md');

const START = '<!-- toc:start (generated by scripts/journal-toc.mjs — do not edit) -->';
const END = '<!-- toc:end -->';

/// GitHub's heading-anchor slug (github-slugger semantics): lowercase, drop
/// anything that is not alphanumeric / space / hyphen / underscore, then
/// replace each space with a hyphen, and disambiguate collisions with
/// -1, -2, ... in document order.
///
/// ⚠️ Spaces are replaced ONE FOR ONE, never collapsed. Removing an em-dash
/// from "source — the" leaves two spaces and therefore "source--the"; a
/// collapsing \s+ would emit "source-the" and silently produce a dead anchor
/// that still looks clickable.
function slugify(text, seen) {
  const base = text
    .toLowerCase()
    .trim()
    .replace(/[^\p{L}\p{N} _-]/gu, '')
    .replace(/ /g, '-');
  const n = seen.get(base) ?? 0;
  seen.set(base, n + 1);
  return n === 0 ? base : `${base}-${n}`;
}

// The release mirror strips `docs/` (`.mirrorignore`), and `zig build test`
// hangs off `drift`, so a public clone would fail its own test suite on a
// missing journal. Absent + --check is a clean skip; absent + regen is an
// error, because you asked to rewrite a file that is not there.
if (!existsSync(JOURNAL)) {
  if (!process.argv.includes('--check')) {
    console.error(`journal-toc: ${JOURNAL} not found — nothing to regenerate`);
    process.exit(2);
  }
  console.log('journal-toc: docs/journal.md absent — skipping (stripped by .mirrorignore in a release clone).');
  process.exit(0);
}

const source = readFileSync(JOURNAL, 'utf8');
const lines = source.split('\n');

// Collect `### N. Title` headers. Anchors must be slugged from the FULL
// heading text (number included) — that is what the renderer sees.
const seen = new Map();
const entries = [];
for (const line of lines) {
  const m = /^### (\d+)\.\s+(.*)$/.exec(line);
  if (!m) continue;
  const heading = line.slice(4);
  entries.push({ n: Number(m[1]), title: m[2].trim(), anchor: slugify(heading, seen) });
}

if (entries.length === 0) {
  console.error('journal-toc: no `### N.` headers found — refusing to write an empty index');
  process.exit(2);
}

const first = entries[0].n;
const last = entries[entries.length - 1].n;

const toc = [
  START,
  '',
  '<details>',
  `<summary><strong>Section index</strong> — §${first}–§${last} ` +
    `(${entries.length} entries; regenerate with <code>node scripts/journal-toc.mjs</code>)</summary>`,
  '',
  ...entries.map((e) => `- [§${e.n} — ${e.title}](#${e.anchor})`),
  '',
  '</details>',
  '',
  END,
].join('\n');

const startIdx = source.indexOf(START);
const endIdx = source.indexOf(END);

let updated;
if (startIdx !== -1 && endIdx !== -1) {
  updated = source.slice(0, startIdx) + toc + source.slice(endIdx + END.length);
} else if (startIdx !== -1 || endIdx !== -1) {
  console.error('journal-toc: found one marker but not the other — fix docs/journal.md by hand');
  process.exit(2);
} else {
  // First run: insert after the intro blockquote, before the first section.
  const firstHeader = lines.findIndex((l) => /^### \d+\./.test(l));
  const head = lines.slice(0, firstHeader).join('\n').replace(/\n+$/, '');
  const rest = lines.slice(firstHeader).join('\n');
  updated = `${head}\n\n${toc}\n\n${rest}`;
}

if (process.argv.includes('--check')) {
  if (updated !== source) {
    console.error(
      `journal-toc: index is stale (${entries.length} sections, §${first}–§${last}).\n` +
        'Run: node scripts/journal-toc.mjs',
    );
    process.exit(1);
  }
  console.log(`journal-toc: index current (${entries.length} sections, §${first}–§${last})`);
  process.exit(0);
}

writeFileSync(JOURNAL, updated);
console.log(`journal-toc: wrote ${entries.length} entries (§${first}–§${last})`);
